### ISSUE TITLE
Bug on collections having overridden values

### ISSUE THREAD

**Issue by ermand** [spryker/support#103]
This is a bug related to collection having overridden values.

* [X] bug
* [ ] enhancement

For questions please consult the [Spryker Forum](http://discuss.spryker.com/).

If possible please provide the exact versions of the bundles involved.
- "spryker/propel": "2.3.8",
- "spryker/glossary": "2.3.0",

### What you did
We are trying to execute the following query and noticed that after executing `->find()` on this query the records in collection are overridden by the last record.
```php
<?php

/**
 * @param int $idMapping
 *
 * @return \Orm\Zed\Cms\Persistence\SpyCmsGlossaryKeyMappingQuery
 */
public function queryGlossaryWithOverrideByMappingIdAndLocaleId($idMapping)
{
    $query = $this->queryGlossaryKeyMappings();
    $query->filterByIdCmsGlossaryKeyMapping($idMapping)
        ->useGlossaryKeyQuery()
            ->withColumn(SpyGlossaryKeyTableMap::COL_KEY, self::KEY)
            ->useSpyGlossaryTranslationQuery(null, Criteria::LEFT_JOIN)
                ->withColumn(SpyGlossaryTranslationTableMap::COL_VALUE, self::TRANS)
                ->withColumn(SpyGlossaryTranslationTableMap::COL_FK_LOCALE, self::FK_LOCALE)
            ->endUse()
        ->endUse();

    return $query;
}
```

### Actual Behavior
All the records in collection object from `vendor/propel/propel/src/Propel/Runtime/Formatter/ObjectFormatter.php` `format` method contain the same content as the last record. To reproduce it please have a record in `spy_cms_glossary_key_mapping` and at least 3 records in `spy_glossary_translation` with the same key `fk_glossary_key` as `spy_cms_glossary_key_mapping .fk_glossary_key`.

**Note;** After debugging we figured out that the issue is at `Map/SpyCmsGlossaryKeyMappingTableMap.php` and `populateObject` method, which is not rehydrating the object.

### Expected Behavior
The records in collection object should be not overridden. Each one should contain the content it fetches from database.

**Comment by lmanzke** [comment]
Hey @ermand,

this is sort of a Propel bug, unfortunately. It has to do with the Propel instance pooling. Short term, a `Propel::disableInstancePooling()` will help solve this. However, it may have an impact on performance.

The root cause is this: Propel caches instances of entities by a hash that is based on the ID (or maybe primary key, but in the Spryker case, this is mostly the same). If we have a join from Mapping to Key to Translation, then you get back an entity with extra fields. The instance of this entity is cached based on the mapping ID. However, this makes it tricky: If you now have a join to multiple translations (because of the locale), Propel recognizes that a mapping with the same ID already resides in the cache and returns the first one. I see you already figured this out (the entity is not repopulated).

Solutions to the problems: 
- Disable instance pooling by means of `Propel::disableInstancePooling()`
- Do the join the other way around: From translation via glossary key to the mapping (then filter) - it will have the same record output, but correct this time. Probably the effort for this is not too high.
- Use a different formatter in the query

I'd also try to solve this on the Propel side, because this behavior will definitely frustrate people. I can imagine the effort involved in debugging this in the first place. I already did this once myself.

**Comment by ermand** [comment]
@lmanzke thanks a lot for your reply. As a quick solution, I switched back to run this as a raw query instead of using Propel. I'll be watching over the progress from Propel side and if there is a fix, then I'll switch back on using the Propel query.

**Comment by AndromedaXP** [comment]
Where is this issue fixed?
