### ISSUE TITLE
[Session] Switch to SessionHandlerRedisLocking not possible

### ISSUE THREAD

**Issue by bazoo0815** [spryker/support#120]
This is a

* [x] bug
* [ ] enhancement

### What you did

I experienced problems on a local docker-ized demoshop setup under Ubuntu 16.04.
In the checkout, an error occured on proceeding from step 'shipping' to 'payment':

> YVES Exception
> 
> Spryker\Shared\ZedRequest\Client\Exception\RequestException - Server error: `POST http://nginx-backend/calculation/gateway/recalculate` resulted in a `500 Internal Server Error` response:
> ZED Exception
> 
> ZED Exception
> 
> Error - Call to a member function getIdCountry() on null
> in /var/www/html/vendor/spryker/product-option/src/Spryker/Zed/ProductOption/Persistence/ProductOptionQueryContainer.php (277)
> 
> Url:/calculation/gateway/recalculate

The reason seems to be a race condition on reading/writing the session from Redis.
I found an implementation of a locking mechanism for Redis sessions in the bundle spryker/session, but after switching the session handler from 'redis' (`SessionHandlerRedis`) to 'redis_locking' (`SessionHandlerRedisLocking`) in the config, another error occured due to the implementation of `\Spryker\Shared\Session\Business\Model\SessionFactory::registerRedisLockingSessionHandler()`.
Currently it doesn't return the handler (only `void`), but that is required in `\Pyz\Yves\Application\Plugin\Provider\SessionServiceProvider::setSessionStorageHandler()`.

### Proposal for code change

My suggestion is to change the code in `src/Spryker/Shared/Session/Business/Model/SessionFactory.php` (line 92) to this (or in any other way that will return the handler properly):

```
    /**
     * @param string $dsn
     *
     * @return \Spryker\Shared\Session\Business\Handler\SessionHandlerRedisLocking
     */
    public function registerRedisLockingSessionHandler(string $dsn)
    {
        $handler = $this->createRedisLockingSessionHandler($dsn);
        $this->setSessionSaveHandler($handler);
        return $handler;
    }
```

Thx.

Best,
Bernd

**Comment by aurisl** [comment]
Hi,

Can you tell me what version of ProductOption, Shipment, TaxProductConnector bundle you are using?

**Comment by ThomasKuehnel** [comment]
Hi Bernd,

your issue is likely not related to registering the locking Redis session-handler. `\Spryker\Shared\Session\Business\Model\SessionFactory::registerRedisLockingSessionHandler()` is not called from `\Pyz\Yves\Application\Plugin\Provider\SessionServiceProvider::setSessionStorageHandler()`. 
Please see https://github.com/spryker/demoshop/blob/master/src/Pyz/Yves/Application/Plugin/Provider/SessionServiceProvider.php#L193. 
`\Spryker\Shared\Session\Business\Model\SessionFactory::createRedisLockingSessionHandler()` is called instead, which returns an instance of the locking Redis session-handler (`https://github.com/spryker/Session/blob/master/src/Spryker/Shared/Session/Business/Model/SessionFactory.php#L106`). 

If it still keeps failing for you due to registering this session handler, please provide a stack-trace of the error so we can try to analyze this more thoroughly.

Cheers

**Comment by bazoo0815** [comment]
Hi Thomas, it seems this issue is now obsolete, because the bundle `spryker/session` has been changed and therefore also the implementation of the session in the demoshop (`\Pyz\Yves\Application\Plugin\Provider\SessionServiceProvider` is completely gone). I will try to update our codebase and change it accordingly.
Thx anyway.
