### ISSUE TITLE
Urls are case sensitive but redis keys are not

### ISSUE THREAD

**Issue by mruoss** [spryker/support#149]
This is a

* [x] bug

### What you did

Let's say you have a cms page with url `/thisIsMyPage`. Now you change the URL to `/thisismypage` and a redirect from the old to the new URL. The UrlCollector will try to create two entries in redis with keys `de.url./thisIsMyPage` and `de.url./thisismypage`. However, in Redis, keys are case insensitive. This results in an error `duplicate key value violates unique constraint "spy_touch_storage-unique-fk_locale"`. 

I think URLs should be kept case insensitive and hence the check that was introduced in https://github.com/spryker/Url/compare/2.2.0...2.3.0 should check URL existence case insensitively.

**Comment by mruoss** [comment]
Just found this thread about case sensivity: https://github.com/propelorm/Propel2/issues/1332

**Comment by tvaleriy** [comment]
Thank you for your feedback. We are going to fix this. I will inform when it is fixed.

**Comment by tvaleriy** [comment]
Should be finally fixed in:
https://github.com/spryker/category/releases/tag/4.15.0
https://github.com/spryker/cms/releases/tag/7.2.0
https://github.com/spryker/cms-gui/releases/tag/5.2.0
https://github.com/spryker/navigation-gui/releases/tag/2.4.0
https://github.com/spryker/product-set/releases/tag/1.4.0
https://github.com/spryker/product-set-gui/releases/tag/2.2.0
https://github.com/spryker/url/releases/tag/3.5.0.
