### ISSUE TITLE
xsd.spryker.com

### ISSUE THREAD

**Issue by ridculy** [spryker/support#178]
This is a Problem with xsd.spryker.com the definition for TransferObjects is not there anymore. 
So my XML Files for Transfers are not Valid anymore.

* [x] bug
* [ ] enhancement

**Comment by tvaleriy** [comment]
It seems connected with recent updates of PHPStorm. We need to find out what has to be changed on our side to match how PHPStorm is working with xml vs xsd.

**Comment by tvaleriy** [comment]
Or maybe not.
Anyway, thanks for pointing out to this problem. We are on it.

**Comment by tvaleriy** [comment]
Hi @ridculy,
this should have been finally fixed in next modules:
https://github.com/spryker/oms/releases/tag/10.2.0
https://github.com/spryker/propel/releases/tag/3.13.0
https://github.com/spryker/state-machine/releases/tag/2.6.0
https://github.com/spryker/transfer/releases/tag/3.13.0
https://github.com/spryker/development/releases/tag/3.21.5
https://github.com/spryker/index-generator/releases/tag/1.0.1

Best,
Spryker Support Team
