### ISSUE TITLE
symfony v2 bundle must still be used

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#179]
This is a

* [] bug
* [x] enhancement

silex/silex                                v1.3.6  
spryker/symfony                      3.1.4

### What you did
composer is still using symfony/http-foundation  v2.8.34 because silex/silex 1.3.6 requires
```
symfony/event-dispatcher ~2.3|3.0.*
symfony/http-foundation ~2.3|3.0.*
symfony/http-kernel ~2.3|3.0.*
symfony/routing ~2.3|3.0.*
```

```
spryker/symfony  3.1.4  requires  symfony/security (^2.6.13 || ^3.0.0) 
```
```
symfony/security     v3.2.14  requires  symfony/http-foundation (~2.8.31|~3.2.14)  
```

There is no v3 of symfony/http-foundation which fits all requirements. So the information was that spryker finished the migration to symfony v3 in january. So when will the problem with silex v1.3.6 be solved?

**Comment by tvaleriy** [comment]
Thank you for the question. At the moment we are hardly working to solve this. Unfortunately can't tell any time frame at the moment.

**Comment by ridculy** [comment]
Why're releasing SF 3 when it's not ready ?

**Comment by stereomon** [comment]
Sorry for the inconvenience here. The update was not about updating all Symfony components, this update was only a small step into the right direction and covers only the Form component.

We are still working hard on this whole update topic.

**Comment by AndromedaXP** [comment]
So what is the roadmap to fix this problems with an outdated silex bundle?

**Comment by tvaleriy** [comment]
The plan is to get rid of silex. Unfortunately I can't tell any time frame or something. We are working hard on the topic.

**Comment by AndromedaXP** [comment]
silex still brings us trouble e.g. unfixed bugs like https://github.com/symfony/symfony/pull/21849 in the UNSUPPORTED! spryker version
symfony/http-kernel                     v3.0.9
What is the actual plan here regarding silex?

**Comment by PhilinTv** [comment]
Hey @AndromedaXP ,

We know about this issue and prepare the infrastructural changes which will bring us to a stable setup. More information and chosen technology we will share once it's ready for publicity, the upgrade is planned for Jan 2019.

If you have questions require tech support on your project, in order to avoid the mentioned issues, let me know. We will arrange a support workshop.

**Comment by AndromedaXP** [comment]
If the projectspecific upgrade changes from spryker side are heavy again, we would like to have a manual/howto.

**Comment by PhilinTv** [comment]
For sure we will support you with the migration/upgrade guides.

**Comment by tvaleriy** [comment]
Hi @ridculy and @AndromedaXP,
the solution for this problem is to update to the latest version of spryker/silexphp and to remove silex/silex and spryker/pimple. You probably will see some conflicts with some other modules but they should be easily fixable.

Please let us know if you have further questions. In the meantime I'll close this ticket.

Best,
Spryker Support Team
