### ISSUE TITLE
Exception when saving a quote with same name

### ISSUE THREAD

**Issue by AndromedaXP** [spryker/support#252]
This is a

* [x] bug
* [ ] enhancement

spryker/persistent-cart                 1.4.1
spryker/quote                           2.4.1

### What you did
Customer wants to save cart (create) with a name that already exists in db, because of unique index (name, customer) this will throw an exception
PersistentCartFacade:createQuote

### Expected Behavior
Exception should be catched and QuoteResponseTransfer should have an error message attached.

**Comment by tvaleriy** [comment]
Hi @AndromedaXP, could you please also write the version of spryker/multi-cart?
Because using latest master branch of spryker-shop/suite I can't reproduce it.
Also I can't reproduce it even if downgrade mentioned module to mentioned versions.
Trying to create a cart with the same name gives me the cart "the_same_name 1".

**Comment by AndromedaXP** [comment]
This is because you have the ResolveQuoteNameBeforeQuoteCreatePlugin added to DP.
We don't have this because we don't want the name to be changed in saving process like "the_same_name 1"

**Comment by tvaleriy** [comment]
Thank you for the report. I will notify when it is fixed and released.

**Comment by andriichekanov** [comment]
Hi @AndromedaXP 
I'm a product owner from a Spryker b2b team, and unfortunately, we can fix this bug, because of "ResolveQuoteNameBeforeQuoteCreatePlugin" mandatory plugin for a MultiCart. If we allow to disable it, then we should additional possible behavior for a catch side effects for a "Quotation process," "Reorder," "Convert to a Shopping list to Cart," and Approval process, features.
We can't support behaviors that will come with the deactivation of the mandatory Plugins on the project.
