### ISSUE TITLE
SprykerShop SubFormFilter breaks the SubFormPluginCollection Iterator

### ISSUE THREAD

**Issue by dantleech** [spryker/support#271]
This is a

* [x] bug
* [ ] enhancement

```
spryker-shop/checkout-page                            1.7.0              CheckoutPage module                              
spryker/step-engine                                   3.1.4              StepEngine module
```

### What you did

Implement a SubFormFilter Plugin in SprykerShop which filtered out a plugin at an index 0.

The `spryker/checkout/src/Spryker/Yves/Checkout/Form/Filter/SubFormFilter.php` unsets the index.

### Actual Behavior

The [Iterator](https://github.com/spryker/step-engine/blob/master/src/Spryker/Yves/StepEngine/Dependency/Plugin/Form/SubFormPluginCollection.php) returns empty, as it checks if it's valid on the current index (0). 

### Expected Behavior

The iterator to return the contents of the collection.

**Comment by tvaleriy** [comment]
Thank you for the report. Internal ticket is created. I will notify if/when it is fixed and released.

**Comment by tvaleriy** [comment]
Hi @dantleech, sorry that it took so long to investigate/fix it.
Actually it has been fixed in https://github.com/spryker/checkout/releases/tag/4.2.1
https://github.com/spryker/step-engine/releases/tag/3.2.0
https://github.com/spryker-shop/checkout-page/releases/tag/1.7.1.

Best,
Spryker Support Team
