### ISSUE TITLE
Can not use multiple data providers when using FormCollectionHandler

### ISSUE THREAD

**Issue by rgex** [spryker/support#55]
The getFormData always sets the same dataProvider for all forms

    public function provideDefaultFormData(AbstractTransfer $dataTransfer)
    {
        $dataTransfer = $this->getFormData($dataTransfer);
        foreach ($this->getForms($dataTransfer) as $form) {
            $form->setData($dataTransfer);
        }
    }

--

    protected function getFormData(QuoteTransfer $quoteTransfer)
    {
        if ($this->dataProvider !== null) {
            return $this->dataProvider->getData($quoteTransfer);
        }
        return $quoteTransfer;
    }

**Comment by tamasnyulas** [comment]
The concept is that the step engine is manipulating one and only one data transfer. If there are multiple forms in a collection for a given step then they need to share the same data transfer because the provider returns an instance of the same type of data transfer filled with some data that is necessary for the current step.

So it's intended that how it currently works, could you explain why do you think that this is a bug?

**Comment by rgex** [comment]
Let's say that we have again the address form on the summary page.
In this case we want to reuse the dataprovider we already used.
Also we don't want the user to go to the place order step but stay on the summary step page.

**Comment by tamasnyulas** [comment]
You should probably inject your address form data provider to the summary form data provider, so you can get every data you need then, then merge the data transfers manually however you need it.

**Comment by the-colorant** [comment]
@rgex do you have more questions open with regards to this issue?
