### ISSUE TITLE
Wrong rounding for discount amount in Zed

### ISSUE THREAD

**Issue by rgex** [spryker/support#75]
To reporduce the bug:
-> Create a fixed voucher with an amount of e.g. 17,99 €
-> Save
-> Voucher amount will be changed to 17,98 € automatically

It appears that this is more a PHP issue as (int)(17.99*100) will return 1798 instead of 1799 as expected.
May be the int cast could be replaced by a round() as Alberto suggested.

**Comment by darius-telycenas** [comment]
http://php.net/manual/en/language.types.integer.php has **Warning** _"Never cast an unknown fraction to integer, as this can sometimes lead to unexpected results"._ with an example ↓
```
<?php
echo (int) ( (0.1+0.7) * 10 ); // echoes 7!
?>
```
http://www.xkcd.com/217/ :)

**Comment by aurisl** [comment]
Hi,

What discount bundle version are you using? Cant reproduce it, and we don't have explicit cast to int for voucher creation.

Btw, Labas Dariau :)

**Comment by aymanrb** [comment]
Well I believe the bug is there in the Spryker DemoShop repo.

I had a clean installation from the [Documentation](http://spryker.github.io/getting-started/installation/guide/) and I was able to reproduce the bug using @rgex steps.

The int casting actually happens in the ORM file and not within the discount bundle itself.

It's in the following file's `setAmount()` method: `src/Orm/Zed/Discount/Persistence/Base/SpyDiscount.php`

```
if ($v !== null) {
   $v = (int) $v;
}
````

**Comment by dereuromark** [comment]
Did you overwrite this method to use round() instead for now?
@aurisl Can we implement something like this for the core here maybe, as well?

**Comment by dereuromark** [comment]
https://github.com/spryker/Discount/releases/tag/3.2.2 fixes the rounding issue, see the test cases for details.
Thank you for reporting this.
