### ISSUE TITLE
collector:storage:flush behaviour

### ISSUE THREAD

**Issue by stefankleff** [spryker/support#76]
1. Currently a redis FLUSHALL is emitted and clears all redis databases including storage specific one as well as the session data db. A solution would be to use FLUSHDB instead.
2. The store environment variable is not respected. All storages of all shops will be deleted. This is very dangerous during emergency fixing and during the setup of new stores. Please use some kind of multidelete which respects the namespace of the current environment and shop.

**Comment by the-colorant** [comment]
We'll take care of this shortly.

**Comment by dereuromark** [comment]
@stefankleff 
Looking into this, we could not find such a `collector:storage:flush` command.
Is that something you implemented on your side?
Because at our end we only have the following commands available:

  - vendor/bin/console collector:storage:export
  - vendor/bin/console collector:search:export

There is however a `redis-cli -p 10009 FLUSHALL` inside
```
function resetDataStores {
}
```
but this script is only to be used for local development.

Are you using that also for production mode?
We are open to suggestions, though, if that script should none-the-less be restricted to more specified commands.

**Comment by dereuromark** [comment]
We will close this for now. Please let us know if we need to reopen. We will need further information here then, though.
