### ISSUE TITLE
[NEWSLETTER] assignCustomerToExistingSubscriber functionality not implement

### ISSUE THREAD

**Issue by harmavenso** [spryker/support#82]
This is a
- [x] bug
- [ ] enhancement

newsletter bundle 2.0.1
### What you did

Register for a newsletter first as guest, then as customer, with the same email address.
### Actual Behavior

spy_newsletter_subscription table is updated, but spy_newsletter_subscriber is not.
### Expected Behavior

As the method assignCustomerToExistingSubscriber in the SubscriberManager implies, the registered user subscriber should be "merged" with the existing guest subscriber: the fk_customer should be set after registering for a newsletter.

**Comment by dereuromark** [comment]
I tried to reproduce, but as long as the `$newsletterSubscriberTransfer` contains a 

    $newsletterSubscriberTransfer->getFkCustomer();

going into the method, that one is also stored as expected in the subscriber entity:

```php
        $subscriberEntity->setFkCustomer($subscriber->getFkCustomer());
        $subscriberEntity->save();
```

It would make sense to enforce the existence here, though, to avoid silent no-ops:
```php
    /**
     * @param \Generated\Shared\Transfer\NewsletterSubscriberTransfer $subscriber
     *
     * @return void
     */
    public function assignCustomerToExistingSubscriber(NewsletterSubscriberTransfer $subscriber)
    {
        $subscriber->requireFkCustomer();

        $subscriberEntity = $this->queryContainer->querySubscriber()
            ->findOneByEmail($subscriber->getEmail());
        if ($subscriberEntity === null) {
            return;
        }

        $subscriberEntity->setFkCustomer($subscriber->getFkCustomer());
        $subscriberEntity->save();
    }
```

Do you agree with this?

We could even throw an exception if the entity is not found, as this would also be unexpected behavior.

**Comment by harmavenso** [comment]
Your improvements look good to me, but the problem is that the method assignCustomerToExistingSubscriber is never called. It should probably be part in some way of processNewsletterSubscriptions as it also needs to circumvent or add to the isAlreadySubscribed logic.

**Comment by harmavenso** [comment]
Additionally - tho i'm not sure if this is core behavior - there are two types of newsletters for this scenario. The guest subscriber has a different newsletter type, so either this would have to be updated too (to CUSTOMER_TYPE), either in core or in the project.

**Comment by dereuromark** [comment]
The `assignCustomerToExistingSubscriber()` method is something you must hook in on your own on project level.
We as core cannot make assumptions here, the project could either do this together or asynchronous, e.g. when someone signs up first and at some later time registers for the newsletter (or vice versa).

As for your 2nd comment, this must be project specific.
If it is successfully assigned you might want to change the type here.
What we can do here, is to provide a bool result instead of void, so it will be clear to you if `assignCustomerToExistingSubscriber()` did actually find a subscriber  and added the foreign key constraint.
Upon that information you can then invoke any additional logic involving the type update.

We would like to provide a patch for you here the next days.

**Comment by harmavenso** [comment]
I've implemented assignCustomerToExistingSubscriber in the project, and it works as expected.

I've updated our export tool, so right now there's also not much pressure with regards to the newsletter types.

**Comment by dereuromark** [comment]
Cool, alright, thank you for the update.
We are still in QA for the promised patch, I will update you once it has been released.

**Comment by dereuromark** [comment]
As promised here the released minor: https://github.com/spryker/Newsletter/releases/tag/2.1.0
